name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Semver tag
        required: true

jobs:
  release:
    runs-on: ubuntu-20.04
    timeout-minutes: 20

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Install ghlog
        run: deno install -A https://deno.land/x/ghlog/ghlog.ts 

      - name: Generate Release Notes
        run: ghlog ${{ github.repository }} -v '${{ github.event.inputs.tag }}'

      - name: Release v${{ github.event.inputs.tag }}
        uses: ncipollo/release-action@v1
        with:
          tag: '${{ github.event.inputs.tag }}'
          name: 'v${{ github.event.inputs.tag }}'
          bodyFile: 'CHANGELOG.md'
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
